main: me.wsman217.healthblocker.HealthBlocker
name: HealthBlocker
version: ${project.version}
author: wsman217
depend: [CrazyAdvancementsAPI]
api-version: "1.14"

commands:
  health:
    description: "Used for info about the HealthBlocker plugin."
  healthfood:
    description: "Not useful"
  euphoriaranks:
    description: "Why?"
    permission: "HealthBlocker.admin"
  convertfood:
    description: "eh"
  evogive:
    description: "lol"
    permission: "HealthBlocker.admin"
  healthtest:
    description: "helpful"
    permission: "healthblocker.testcommand"
    default: op
permissions:
  HealthBlocker.*:
    default: op
    children:
      HealthBlocker.admin: true
  HealthBlocker.admin:
    description: "Admin permissions"